<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>Software</RootNamespace>
    <AssemblyName>Software</AssemblyName>
    <ApplicationIcon>Resources\MainIcon.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="10.0.12" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.12" />
    <PackageReference Include="LibUsbDotNet" Version="3.0.224" />
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.5.1.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" Version="7.5.1.1" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
    <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Settings.AppSettings" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
    <Content Include="Resources\BuiltInScript.js" />
    <Content Include="Resources\DefaultConfigScript.js" />
    <None Include="libusb-1.0.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
